version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "3001:80" # Map port 80 in the container to 3001 on the host
    environment:
      REACT_APP_API_URL: http://0.0.0.0:3000
    volumes:
      - .:/app # Mount local changes for development (optional)
